version: '3.4'

services:
  rascal:
    container_name: myrascal
    image: rascal
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
        - ./app:/usr/app
    ports:
      - 3003:3000

    command: tail -f /dev/null # keep open container
